// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: dag.proto

package scenario_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DAG_TYPE int32

const (
	DAG_TYPE_HTTP     DAG_TYPE = 0
	DAG_TYPE_CRON_JOB DAG_TYPE = 1
)

// Enum value maps for DAG_TYPE.
var (
	DAG_TYPE_name = map[int32]string{
		0: "HTTP",
		1: "CRON_JOB",
	}
	DAG_TYPE_value = map[string]int32{
		"HTTP":     0,
		"CRON_JOB": 1,
	}
)

func (x DAG_TYPE) Enum() *DAG_TYPE {
	p := new(DAG_TYPE)
	*p = x
	return p
}

func (x DAG_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DAG_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_dag_proto_enumTypes[0].Descriptor()
}

func (DAG_TYPE) Type() protoreflect.EnumType {
	return &file_dag_proto_enumTypes[0]
}

func (x DAG_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DAG_TYPE.Descriptor instead.
func (DAG_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{0}
}

type DAG_STATUS int32

const (
	DAG_STATUS_ACTIVE   DAG_STATUS = 0
	DAG_STATUS_INACTIVE DAG_STATUS = 1
)

// Enum value maps for DAG_STATUS.
var (
	DAG_STATUS_name = map[int32]string{
		0: "ACTIVE",
		1: "INACTIVE",
	}
	DAG_STATUS_value = map[string]int32{
		"ACTIVE":   0,
		"INACTIVE": 1,
	}
)

func (x DAG_STATUS) Enum() *DAG_STATUS {
	p := new(DAG_STATUS)
	*p = x
	return p
}

func (x DAG_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DAG_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_dag_proto_enumTypes[1].Descriptor()
}

func (DAG_STATUS) Type() protoreflect.EnumType {
	return &file_dag_proto_enumTypes[1]
}

func (x DAG_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DAG_STATUS.Descriptor instead.
func (DAG_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{1}
}

type DAG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug   string     `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Type   DAG_TYPE   `protobuf:"varint,4,opt,name=type,proto3,enum=scenario_service.DAG_TYPE" json:"type,omitempty"`
	Status DAG_STATUS `protobuf:"varint,5,opt,name=status,proto3,enum=scenario_service.DAG_STATUS" json:"status,omitempty"`
}

func (x *DAG) Reset() {
	*x = DAG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DAG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAG) ProtoMessage() {}

func (x *DAG) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAG.ProtoReflect.Descriptor instead.
func (*DAG) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{0}
}

func (x *DAG) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DAG) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DAG) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *DAG) GetType() DAG_TYPE {
	if x != nil {
		return x.Type
	}
	return DAG_TYPE_HTTP
}

func (x *DAG) GetStatus() DAG_STATUS {
	if x != nil {
		return x.Status
	}
	return DAG_STATUS_ACTIVE
}

type CreateDAGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dag *DAG `protobuf:"bytes,1,opt,name=dag,proto3" json:"dag,omitempty"`
}

func (x *CreateDAGRequest) Reset() {
	*x = CreateDAGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDAGRequest) ProtoMessage() {}

func (x *CreateDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDAGRequest.ProtoReflect.Descriptor instead.
func (*CreateDAGRequest) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDAGRequest) GetDag() *DAG {
	if x != nil {
		return x.Dag
	}
	return nil
}

type GetDAGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDAGRequest) Reset() {
	*x = GetDAGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDAGRequest) ProtoMessage() {}

func (x *GetDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDAGRequest.ProtoReflect.Descriptor instead.
func (*GetDAGRequest) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{2}
}

func (x *GetDAGRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllDAGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *Filters `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *GetAllDAGRequest) Reset() {
	*x = GetAllDAGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDAGRequest) ProtoMessage() {}

func (x *GetAllDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDAGRequest.ProtoReflect.Descriptor instead.
func (*GetAllDAGRequest) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllDAGRequest) GetFilter() *Filters {
	if x != nil {
		return x.Filter
	}
	return nil
}

type DAGList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DAGs  []*DAG `protobuf:"bytes,1,rep,name=DAGs,proto3" json:"DAGs,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *DAGList) Reset() {
	*x = DAGList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DAGList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGList) ProtoMessage() {}

func (x *DAGList) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGList.ProtoReflect.Descriptor instead.
func (*DAGList) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{4}
}

func (x *DAGList) GetDAGs() []*DAG {
	if x != nil {
		return x.DAGs
	}
	return nil
}

func (x *DAGList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeleteDAGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDAGRequest) Reset() {
	*x = DeleteDAGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDAGRequest) ProtoMessage() {}

func (x *DeleteDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDAGRequest.ProtoReflect.Descriptor instead.
func (*DeleteDAGRequest) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDAGRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDAGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dag *DAG `protobuf:"bytes,1,opt,name=dag,proto3" json:"dag,omitempty"`
}

func (x *UpdateDAGRequest) Reset() {
	*x = UpdateDAGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDAGRequest) ProtoMessage() {}

func (x *UpdateDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDAGRequest.ProtoReflect.Descriptor instead.
func (*UpdateDAGRequest) Descriptor() ([]byte, []int) {
	return file_dag_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDAGRequest) GetDag() *DAG {
	if x != nil {
		return x.Dag
	}
	return nil
}

var File_dag_proto protoreflect.FileDescriptor

var file_dag_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5, 0x01, 0x0a, 0x03, 0x44, 0x41, 0x47, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69,
	0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3b,
	0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x41, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x27, 0x0a, 0x03, 0x64, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x52, 0x03, 0x64, 0x61, 0x67, 0x22, 0x1f, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x44, 0x41, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x41, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x22, 0x4a, 0x0a, 0x07, 0x44, 0x41, 0x47, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29,
	0x0a, 0x04, 0x44, 0x41, 0x47, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73,
	0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x44, 0x41, 0x47, 0x52, 0x04, 0x44, 0x41, 0x47, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x41, 0x47, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x41, 0x47,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x03, 0x64, 0x61, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x52, 0x03, 0x64, 0x61, 0x67,
	0x2a, 0x22, 0x0a, 0x08, 0x44, 0x41, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x08, 0x0a, 0x04,
	0x48, 0x54, 0x54, 0x50, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52, 0x4f, 0x4e, 0x5f, 0x4a,
	0x4f, 0x42, 0x10, 0x01, 0x2a, 0x26, 0x0a, 0x0a, 0x44, 0x41, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x32, 0xe4, 0x02, 0x0a,
	0x0a, 0x44, 0x41, 0x47, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x41, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47,
	0x12, 0x3d, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1f, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x41,
	0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x12,
	0x47, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x22, 0x2e, 0x73, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x44, 0x41, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x44, 0x41, 0x47, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x22, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x41, 0x47, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x43,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x41, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73,
	0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x44, 0x41, 0x47, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dag_proto_rawDescOnce sync.Once
	file_dag_proto_rawDescData = file_dag_proto_rawDesc
)

func file_dag_proto_rawDescGZIP() []byte {
	file_dag_proto_rawDescOnce.Do(func() {
		file_dag_proto_rawDescData = protoimpl.X.CompressGZIP(file_dag_proto_rawDescData)
	})
	return file_dag_proto_rawDescData
}

var file_dag_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dag_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dag_proto_goTypes = []interface{}{
	(DAG_TYPE)(0),            // 0: scenario_service.DAG_TYPE
	(DAG_STATUS)(0),          // 1: scenario_service.DAG_STATUS
	(*DAG)(nil),              // 2: scenario_service.DAG
	(*CreateDAGRequest)(nil), // 3: scenario_service.CreateDAGRequest
	(*GetDAGRequest)(nil),    // 4: scenario_service.GetDAGRequest
	(*GetAllDAGRequest)(nil), // 5: scenario_service.GetAllDAGRequest
	(*DAGList)(nil),          // 6: scenario_service.DAGList
	(*DeleteDAGRequest)(nil), // 7: scenario_service.DeleteDAGRequest
	(*UpdateDAGRequest)(nil), // 8: scenario_service.UpdateDAGRequest
	(*Filters)(nil),          // 9: scenario_service.Filters
	(*emptypb.Empty)(nil),    // 10: google.protobuf.Empty
}
var file_dag_proto_depIdxs = []int32{
	0,  // 0: scenario_service.DAG.type:type_name -> scenario_service.DAG_TYPE
	1,  // 1: scenario_service.DAG.status:type_name -> scenario_service.DAG_STATUS
	2,  // 2: scenario_service.CreateDAGRequest.dag:type_name -> scenario_service.DAG
	9,  // 3: scenario_service.GetAllDAGRequest.filter:type_name -> scenario_service.Filters
	2,  // 4: scenario_service.DAGList.DAGs:type_name -> scenario_service.DAG
	2,  // 5: scenario_service.UpdateDAGRequest.dag:type_name -> scenario_service.DAG
	3,  // 6: scenario_service.DAGService.Create:input_type -> scenario_service.CreateDAGRequest
	4,  // 7: scenario_service.DAGService.Get:input_type -> scenario_service.GetDAGRequest
	5,  // 8: scenario_service.DAGService.GetAll:input_type -> scenario_service.GetAllDAGRequest
	7,  // 9: scenario_service.DAGService.Delete:input_type -> scenario_service.DeleteDAGRequest
	8,  // 10: scenario_service.DAGService.Update:input_type -> scenario_service.UpdateDAGRequest
	2,  // 11: scenario_service.DAGService.Create:output_type -> scenario_service.DAG
	2,  // 12: scenario_service.DAGService.Get:output_type -> scenario_service.DAG
	6,  // 13: scenario_service.DAGService.GetAll:output_type -> scenario_service.DAGList
	10, // 14: scenario_service.DAGService.Delete:output_type -> google.protobuf.Empty
	2,  // 15: scenario_service.DAGService.Update:output_type -> scenario_service.DAG
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_dag_proto_init() }
func file_dag_proto_init() {
	if File_dag_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DAG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDAGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDAGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDAGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DAGList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDAGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDAGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dag_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dag_proto_goTypes,
		DependencyIndexes: file_dag_proto_depIdxs,
		EnumInfos:         file_dag_proto_enumTypes,
		MessageInfos:      file_dag_proto_msgTypes,
	}.Build()
	File_dag_proto = out.File
	file_dag_proto_rawDesc = nil
	file_dag_proto_goTypes = nil
	file_dag_proto_depIdxs = nil
}
