CREATE TABLE IF NOT EXISTS email_sms(
    id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(128) NOT NULL,
    otp VARCHAR(12) DEFAULT ''::VARCHAR,
    expires_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);