ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "name" VARCHAR DEFAULT '' NOT NULL;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "photo_url" VARCHAR;
-- ALTER TABLE "user" ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES "company"("id");
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS language_id UUID REFERENCES "language"("id");
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS timezone_id UUID REFERENCES "timezone"("id");