// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: layout.proto

package object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LayoutServiceClient is the client API for LayoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LayoutServiceClient interface {
	CreateAll(ctx context.Context, in *CreateLayoutRequest, opts ...grpc.CallOption) (*GetListLayoutResponse, error)
	Update(ctx context.Context, in *UpdateLayoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAll(ctx context.Context, in *GetListLayoutRequest, opts ...grpc.CallOption) (*GetListLayoutResponse, error)
}

type layoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLayoutServiceClient(cc grpc.ClientConnInterface) LayoutServiceClient {
	return &layoutServiceClient{cc}
}

func (c *layoutServiceClient) CreateAll(ctx context.Context, in *CreateLayoutRequest, opts ...grpc.CallOption) (*GetListLayoutResponse, error) {
	out := new(GetListLayoutResponse)
	err := c.cc.Invoke(ctx, "/object_builder_service.LayoutService/CreateAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) Update(ctx context.Context, in *UpdateLayoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/object_builder_service.LayoutService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) GetAll(ctx context.Context, in *GetListLayoutRequest, opts ...grpc.CallOption) (*GetListLayoutResponse, error) {
	out := new(GetListLayoutResponse)
	err := c.cc.Invoke(ctx, "/object_builder_service.LayoutService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayoutServiceServer is the server API for LayoutService service.
// All implementations must embed UnimplementedLayoutServiceServer
// for forward compatibility
type LayoutServiceServer interface {
	CreateAll(context.Context, *CreateLayoutRequest) (*GetListLayoutResponse, error)
	Update(context.Context, *UpdateLayoutRequest) (*emptypb.Empty, error)
	GetAll(context.Context, *GetListLayoutRequest) (*GetListLayoutResponse, error)
	mustEmbedUnimplementedLayoutServiceServer()
}

// UnimplementedLayoutServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLayoutServiceServer struct {
}

func (UnimplementedLayoutServiceServer) CreateAll(context.Context, *CreateLayoutRequest) (*GetListLayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAll not implemented")
}
func (UnimplementedLayoutServiceServer) Update(context.Context, *UpdateLayoutRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedLayoutServiceServer) GetAll(context.Context, *GetListLayoutRequest) (*GetListLayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedLayoutServiceServer) mustEmbedUnimplementedLayoutServiceServer() {}

// UnsafeLayoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayoutServiceServer will
// result in compilation errors.
type UnsafeLayoutServiceServer interface {
	mustEmbedUnimplementedLayoutServiceServer()
}

func RegisterLayoutServiceServer(s grpc.ServiceRegistrar, srv LayoutServiceServer) {
	s.RegisterService(&LayoutService_ServiceDesc, srv)
}

func _LayoutService_CreateAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).CreateAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LayoutService/CreateAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).CreateAll(ctx, req.(*CreateLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LayoutService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).Update(ctx, req.(*UpdateLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LayoutService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).GetAll(ctx, req.(*GetListLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LayoutService_ServiceDesc is the grpc.ServiceDesc for LayoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LayoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.LayoutService",
	HandlerType: (*LayoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAll",
			Handler:    _LayoutService_CreateAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _LayoutService_Update_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _LayoutService_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "layout.proto",
}
