// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.3
// source: table_menu.proto

package object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TableMenuServiceClient is the client API for TableMenuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TableMenuServiceClient interface {
	Create(ctx context.Context, in *TableMenuRequest, opts ...grpc.CallOption) (*CreateTableMenuResponse, error)
	GetByID(ctx context.Context, in *TableMenuPrimaryKey, opts ...grpc.CallOption) (*TableMenu, error)
	GetAll(ctx context.Context, in *GetAllTableMenusRequest, opts ...grpc.CallOption) (*GetAllTableMenusResponse, error)
	Update(ctx context.Context, in *TableMenu, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *TableMenuPrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tableMenuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTableMenuServiceClient(cc grpc.ClientConnInterface) TableMenuServiceClient {
	return &tableMenuServiceClient{cc}
}

func (c *tableMenuServiceClient) Create(ctx context.Context, in *TableMenuRequest, opts ...grpc.CallOption) (*CreateTableMenuResponse, error) {
	out := new(CreateTableMenuResponse)
	err := c.cc.Invoke(ctx, "/object_builder_service.TableMenuService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableMenuServiceClient) GetByID(ctx context.Context, in *TableMenuPrimaryKey, opts ...grpc.CallOption) (*TableMenu, error) {
	out := new(TableMenu)
	err := c.cc.Invoke(ctx, "/object_builder_service.TableMenuService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableMenuServiceClient) GetAll(ctx context.Context, in *GetAllTableMenusRequest, opts ...grpc.CallOption) (*GetAllTableMenusResponse, error) {
	out := new(GetAllTableMenusResponse)
	err := c.cc.Invoke(ctx, "/object_builder_service.TableMenuService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableMenuServiceClient) Update(ctx context.Context, in *TableMenu, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/object_builder_service.TableMenuService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableMenuServiceClient) Delete(ctx context.Context, in *TableMenuPrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/object_builder_service.TableMenuService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableMenuServiceServer is the server API for TableMenuService service.
// All implementations must embed UnimplementedTableMenuServiceServer
// for forward compatibility
type TableMenuServiceServer interface {
	Create(context.Context, *TableMenuRequest) (*CreateTableMenuResponse, error)
	GetByID(context.Context, *TableMenuPrimaryKey) (*TableMenu, error)
	GetAll(context.Context, *GetAllTableMenusRequest) (*GetAllTableMenusResponse, error)
	Update(context.Context, *TableMenu) (*emptypb.Empty, error)
	Delete(context.Context, *TableMenuPrimaryKey) (*emptypb.Empty, error)
	mustEmbedUnimplementedTableMenuServiceServer()
}

// UnimplementedTableMenuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTableMenuServiceServer struct {
}

func (UnimplementedTableMenuServiceServer) Create(context.Context, *TableMenuRequest) (*CreateTableMenuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTableMenuServiceServer) GetByID(context.Context, *TableMenuPrimaryKey) (*TableMenu, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedTableMenuServiceServer) GetAll(context.Context, *GetAllTableMenusRequest) (*GetAllTableMenusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedTableMenuServiceServer) Update(context.Context, *TableMenu) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTableMenuServiceServer) Delete(context.Context, *TableMenuPrimaryKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTableMenuServiceServer) mustEmbedUnimplementedTableMenuServiceServer() {}

// UnsafeTableMenuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TableMenuServiceServer will
// result in compilation errors.
type UnsafeTableMenuServiceServer interface {
	mustEmbedUnimplementedTableMenuServiceServer()
}

func RegisterTableMenuServiceServer(s grpc.ServiceRegistrar, srv TableMenuServiceServer) {
	s.RegisterService(&TableMenuService_ServiceDesc, srv)
}

func _TableMenuService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMenuServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.TableMenuService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMenuServiceServer).Create(ctx, req.(*TableMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableMenuService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableMenuPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMenuServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.TableMenuService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMenuServiceServer).GetByID(ctx, req.(*TableMenuPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableMenuService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTableMenusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMenuServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.TableMenuService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMenuServiceServer).GetAll(ctx, req.(*GetAllTableMenusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableMenuService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableMenu)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMenuServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.TableMenuService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMenuServiceServer).Update(ctx, req.(*TableMenu))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableMenuService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableMenuPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMenuServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.TableMenuService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMenuServiceServer).Delete(ctx, req.(*TableMenuPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// TableMenuService_ServiceDesc is the grpc.ServiceDesc for TableMenuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TableMenuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.TableMenuService",
	HandlerType: (*TableMenuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TableMenuService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _TableMenuService_GetByID_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _TableMenuService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TableMenuService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TableMenuService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "table_menu.proto",
}
