// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: version_history.proto

package object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VersionHistoryServiceClient is the client API for VersionHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VersionHistoryServiceClient interface {
	GatAll(ctx context.Context, in *GetAllRquest, opts ...grpc.CallOption) (*ListVersionHistory, error)
	UsedForEnv(ctx context.Context, in *UsedForEnvRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Migrate(ctx context.Context, in *ListVersionHistory, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type versionHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVersionHistoryServiceClient(cc grpc.ClientConnInterface) VersionHistoryServiceClient {
	return &versionHistoryServiceClient{cc}
}

func (c *versionHistoryServiceClient) GatAll(ctx context.Context, in *GetAllRquest, opts ...grpc.CallOption) (*ListVersionHistory, error) {
	out := new(ListVersionHistory)
	err := c.cc.Invoke(ctx, "/object_builder_service.VersionHistoryService/GatAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionHistoryServiceClient) UsedForEnv(ctx context.Context, in *UsedForEnvRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/object_builder_service.VersionHistoryService/UsedForEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionHistoryServiceClient) Migrate(ctx context.Context, in *ListVersionHistory, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/object_builder_service.VersionHistoryService/Migrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionHistoryServiceServer is the server API for VersionHistoryService service.
// All implementations must embed UnimplementedVersionHistoryServiceServer
// for forward compatibility
type VersionHistoryServiceServer interface {
	GatAll(context.Context, *GetAllRquest) (*ListVersionHistory, error)
	UsedForEnv(context.Context, *UsedForEnvRequest) (*emptypb.Empty, error)
	Migrate(context.Context, *ListVersionHistory) (*emptypb.Empty, error)
	mustEmbedUnimplementedVersionHistoryServiceServer()
}

// UnimplementedVersionHistoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVersionHistoryServiceServer struct {
}

func (UnimplementedVersionHistoryServiceServer) GatAll(context.Context, *GetAllRquest) (*ListVersionHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatAll not implemented")
}
func (UnimplementedVersionHistoryServiceServer) UsedForEnv(context.Context, *UsedForEnvRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsedForEnv not implemented")
}
func (UnimplementedVersionHistoryServiceServer) Migrate(context.Context, *ListVersionHistory) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedVersionHistoryServiceServer) mustEmbedUnimplementedVersionHistoryServiceServer() {}

// UnsafeVersionHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VersionHistoryServiceServer will
// result in compilation errors.
type UnsafeVersionHistoryServiceServer interface {
	mustEmbedUnimplementedVersionHistoryServiceServer()
}

func RegisterVersionHistoryServiceServer(s grpc.ServiceRegistrar, srv VersionHistoryServiceServer) {
	s.RegisterService(&VersionHistoryService_ServiceDesc, srv)
}

func _VersionHistoryService_GatAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).GatAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.VersionHistoryService/GatAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).GatAll(ctx, req.(*GetAllRquest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionHistoryService_UsedForEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsedForEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).UsedForEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.VersionHistoryService/UsedForEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).UsedForEnv(ctx, req.(*UsedForEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionHistoryService_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVersionHistory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.VersionHistoryService/Migrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).Migrate(ctx, req.(*ListVersionHistory))
	}
	return interceptor(ctx, in, info, handler)
}

// VersionHistoryService_ServiceDesc is the grpc.ServiceDesc for VersionHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VersionHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.VersionHistoryService",
	HandlerType: (*VersionHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GatAll",
			Handler:    _VersionHistoryService_GatAll_Handler,
		},
		{
			MethodName: "UsedForEnv",
			Handler:    _VersionHistoryService_UsedForEnv_Handler,
		},
		{
			MethodName: "Migrate",
			Handler:    _VersionHistoryService_Migrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "version_history.proto",
}
