// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: integration_resource_service.proto

package company_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IntegrationResourceService_CreateIntegrationResource_FullMethodName = "/company_service.IntegrationResourceService/CreateIntegrationResource"
	IntegrationResourceService_GetByUsername_FullMethodName             = "/company_service.IntegrationResourceService/GetByUsername"
)

// IntegrationResourceServiceClient is the client API for IntegrationResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntegrationResourceServiceClient interface {
	CreateIntegrationResource(ctx context.Context, in *CreateIntegrationResourceRequest, opts ...grpc.CallOption) (*IntegrationResource, error)
	GetByUsername(ctx context.Context, in *GetByUsernameRequest, opts ...grpc.CallOption) (*GetByUsernameResponse, error)
}

type integrationResourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationResourceServiceClient(cc grpc.ClientConnInterface) IntegrationResourceServiceClient {
	return &integrationResourceServiceClient{cc}
}

func (c *integrationResourceServiceClient) CreateIntegrationResource(ctx context.Context, in *CreateIntegrationResourceRequest, opts ...grpc.CallOption) (*IntegrationResource, error) {
	out := new(IntegrationResource)
	err := c.cc.Invoke(ctx, IntegrationResourceService_CreateIntegrationResource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationResourceServiceClient) GetByUsername(ctx context.Context, in *GetByUsernameRequest, opts ...grpc.CallOption) (*GetByUsernameResponse, error) {
	out := new(GetByUsernameResponse)
	err := c.cc.Invoke(ctx, IntegrationResourceService_GetByUsername_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationResourceServiceServer is the server API for IntegrationResourceService service.
// All implementations must embed UnimplementedIntegrationResourceServiceServer
// for forward compatibility
type IntegrationResourceServiceServer interface {
	CreateIntegrationResource(context.Context, *CreateIntegrationResourceRequest) (*IntegrationResource, error)
	GetByUsername(context.Context, *GetByUsernameRequest) (*GetByUsernameResponse, error)
	mustEmbedUnimplementedIntegrationResourceServiceServer()
}

// UnimplementedIntegrationResourceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntegrationResourceServiceServer struct {
}

func (UnimplementedIntegrationResourceServiceServer) CreateIntegrationResource(context.Context, *CreateIntegrationResourceRequest) (*IntegrationResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIntegrationResource not implemented")
}
func (UnimplementedIntegrationResourceServiceServer) GetByUsername(context.Context, *GetByUsernameRequest) (*GetByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUsername not implemented")
}
func (UnimplementedIntegrationResourceServiceServer) mustEmbedUnimplementedIntegrationResourceServiceServer() {
}

// UnsafeIntegrationResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrationResourceServiceServer will
// result in compilation errors.
type UnsafeIntegrationResourceServiceServer interface {
	mustEmbedUnimplementedIntegrationResourceServiceServer()
}

func RegisterIntegrationResourceServiceServer(s grpc.ServiceRegistrar, srv IntegrationResourceServiceServer) {
	s.RegisterService(&IntegrationResourceService_ServiceDesc, srv)
}

func _IntegrationResourceService_CreateIntegrationResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIntegrationResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationResourceServiceServer).CreateIntegrationResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationResourceService_CreateIntegrationResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationResourceServiceServer).CreateIntegrationResource(ctx, req.(*CreateIntegrationResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationResourceService_GetByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationResourceServiceServer).GetByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationResourceService_GetByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationResourceServiceServer).GetByUsername(ctx, req.(*GetByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntegrationResourceService_ServiceDesc is the grpc.ServiceDesc for IntegrationResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntegrationResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "company_service.IntegrationResourceService",
	HandlerType: (*IntegrationResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIntegrationResource",
			Handler:    _IntegrationResourceService_CreateIntegrationResource_Handler,
		},
		{
			MethodName: "GetByUsername",
			Handler:    _IntegrationResourceService_GetByUsername_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integration_resource_service.proto",
}
