// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: service_resource.proto

package company_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceResourceClient is the client API for ServiceResource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceResourceClient interface {
	Create(ctx context.Context, in *CreateServiceResourceRequest, opts ...grpc.CallOption) (*ServiceResources, error)
	GetList(ctx context.Context, in *GetListServiceResourceRequest, opts ...grpc.CallOption) (*GetListServiceResourceResponse, error)
	GetById(ctx context.Context, in *ServiceResourcePrimaryKey, opts ...grpc.CallOption) (*ServiceResources, error)
	Update(ctx context.Context, in *UpdateServiceResourceRequest, opts ...grpc.CallOption) (*ServiceResources, error)
	Delete(ctx context.Context, in *ServiceResourcePrimaryKey, opts ...grpc.CallOption) (*EmptyProto, error)
}

type serviceResourceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceResourceClient(cc grpc.ClientConnInterface) ServiceResourceClient {
	return &serviceResourceClient{cc}
}

func (c *serviceResourceClient) Create(ctx context.Context, in *CreateServiceResourceRequest, opts ...grpc.CallOption) (*ServiceResources, error) {
	out := new(ServiceResources)
	err := c.cc.Invoke(ctx, "/company_service.ServiceResource/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceResourceClient) GetList(ctx context.Context, in *GetListServiceResourceRequest, opts ...grpc.CallOption) (*GetListServiceResourceResponse, error) {
	out := new(GetListServiceResourceResponse)
	err := c.cc.Invoke(ctx, "/company_service.ServiceResource/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceResourceClient) GetById(ctx context.Context, in *ServiceResourcePrimaryKey, opts ...grpc.CallOption) (*ServiceResources, error) {
	out := new(ServiceResources)
	err := c.cc.Invoke(ctx, "/company_service.ServiceResource/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceResourceClient) Update(ctx context.Context, in *UpdateServiceResourceRequest, opts ...grpc.CallOption) (*ServiceResources, error) {
	out := new(ServiceResources)
	err := c.cc.Invoke(ctx, "/company_service.ServiceResource/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceResourceClient) Delete(ctx context.Context, in *ServiceResourcePrimaryKey, opts ...grpc.CallOption) (*EmptyProto, error) {
	out := new(EmptyProto)
	err := c.cc.Invoke(ctx, "/company_service.ServiceResource/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceResourceServer is the server API for ServiceResource service.
// All implementations must embed UnimplementedServiceResourceServer
// for forward compatibility
type ServiceResourceServer interface {
	Create(context.Context, *CreateServiceResourceRequest) (*ServiceResources, error)
	GetList(context.Context, *GetListServiceResourceRequest) (*GetListServiceResourceResponse, error)
	GetById(context.Context, *ServiceResourcePrimaryKey) (*ServiceResources, error)
	Update(context.Context, *UpdateServiceResourceRequest) (*ServiceResources, error)
	Delete(context.Context, *ServiceResourcePrimaryKey) (*EmptyProto, error)
	mustEmbedUnimplementedServiceResourceServer()
}

// UnimplementedServiceResourceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceResourceServer struct {
}

func (UnimplementedServiceResourceServer) Create(context.Context, *CreateServiceResourceRequest) (*ServiceResources, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedServiceResourceServer) GetList(context.Context, *GetListServiceResourceRequest) (*GetListServiceResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedServiceResourceServer) GetById(context.Context, *ServiceResourcePrimaryKey) (*ServiceResources, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedServiceResourceServer) Update(context.Context, *UpdateServiceResourceRequest) (*ServiceResources, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedServiceResourceServer) Delete(context.Context, *ServiceResourcePrimaryKey) (*EmptyProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedServiceResourceServer) mustEmbedUnimplementedServiceResourceServer() {}

// UnsafeServiceResourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceResourceServer will
// result in compilation errors.
type UnsafeServiceResourceServer interface {
	mustEmbedUnimplementedServiceResourceServer()
}

func RegisterServiceResourceServer(s grpc.ServiceRegistrar, srv ServiceResourceServer) {
	s.RegisterService(&ServiceResource_ServiceDesc, srv)
}

func _ServiceResource_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceResourceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company_service.ServiceResource/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceResourceServer).Create(ctx, req.(*CreateServiceResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceResource_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListServiceResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceResourceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company_service.ServiceResource/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceResourceServer).GetList(ctx, req.(*GetListServiceResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceResource_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceResourcePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceResourceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company_service.ServiceResource/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceResourceServer).GetById(ctx, req.(*ServiceResourcePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceResource_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceResourceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company_service.ServiceResource/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceResourceServer).Update(ctx, req.(*UpdateServiceResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceResource_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceResourcePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceResourceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company_service.ServiceResource/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceResourceServer).Delete(ctx, req.(*ServiceResourcePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceResource_ServiceDesc is the grpc.ServiceDesc for ServiceResource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceResource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "company_service.ServiceResource",
	HandlerType: (*ServiceResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ServiceResource_Create_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _ServiceResource_GetList_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _ServiceResource_GetById_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ServiceResource_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ServiceResource_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_resource.proto",
}
