// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: api_key_usage.proto

package auth_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiKeyUsageServiceClient is the client API for ApiKeyUsageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiKeyUsageServiceClient interface {
	Get(ctx context.Context, in *GetApiKeyUsageReq, opts ...grpc.CallOption) (*ApiKeyUsage, error)
	CheckAndUpsertLimit(ctx context.Context, in *CheckLimitRequest, opts ...grpc.CallOption) (*CheckLimitResponse, error)
}

type apiKeyUsageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApiKeyUsageServiceClient(cc grpc.ClientConnInterface) ApiKeyUsageServiceClient {
	return &apiKeyUsageServiceClient{cc}
}

func (c *apiKeyUsageServiceClient) Get(ctx context.Context, in *GetApiKeyUsageReq, opts ...grpc.CallOption) (*ApiKeyUsage, error) {
	out := new(ApiKeyUsage)
	err := c.cc.Invoke(ctx, "/auth_service.ApiKeyUsageService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeyUsageServiceClient) CheckAndUpsertLimit(ctx context.Context, in *CheckLimitRequest, opts ...grpc.CallOption) (*CheckLimitResponse, error) {
	out := new(CheckLimitResponse)
	err := c.cc.Invoke(ctx, "/auth_service.ApiKeyUsageService/CheckAndUpsertLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiKeyUsageServiceServer is the server API for ApiKeyUsageService service.
// All implementations must embed UnimplementedApiKeyUsageServiceServer
// for forward compatibility
type ApiKeyUsageServiceServer interface {
	Get(context.Context, *GetApiKeyUsageReq) (*ApiKeyUsage, error)
	CheckAndUpsertLimit(context.Context, *CheckLimitRequest) (*CheckLimitResponse, error)
	mustEmbedUnimplementedApiKeyUsageServiceServer()
}

// UnimplementedApiKeyUsageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApiKeyUsageServiceServer struct {
}

func (UnimplementedApiKeyUsageServiceServer) Get(context.Context, *GetApiKeyUsageReq) (*ApiKeyUsage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedApiKeyUsageServiceServer) CheckAndUpsertLimit(context.Context, *CheckLimitRequest) (*CheckLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAndUpsertLimit not implemented")
}
func (UnimplementedApiKeyUsageServiceServer) mustEmbedUnimplementedApiKeyUsageServiceServer() {}

// UnsafeApiKeyUsageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiKeyUsageServiceServer will
// result in compilation errors.
type UnsafeApiKeyUsageServiceServer interface {
	mustEmbedUnimplementedApiKeyUsageServiceServer()
}

func RegisterApiKeyUsageServiceServer(s grpc.ServiceRegistrar, srv ApiKeyUsageServiceServer) {
	s.RegisterService(&ApiKeyUsageService_ServiceDesc, srv)
}

func _ApiKeyUsageService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApiKeyUsageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyUsageServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.ApiKeyUsageService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyUsageServiceServer).Get(ctx, req.(*GetApiKeyUsageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeyUsageService_CheckAndUpsertLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyUsageServiceServer).CheckAndUpsertLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.ApiKeyUsageService/CheckAndUpsertLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyUsageServiceServer).CheckAndUpsertLimit(ctx, req.(*CheckLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiKeyUsageService_ServiceDesc is the grpc.ServiceDesc for ApiKeyUsageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiKeyUsageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.ApiKeyUsageService",
	HandlerType: (*ApiKeyUsageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ApiKeyUsageService_Get_Handler,
		},
		{
			MethodName: "CheckAndUpsertLimit",
			Handler:    _ApiKeyUsageService_CheckAndUpsertLimit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_key_usage.proto",
}
