// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: sync_user.proto

package auth_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SyncUserServiceClient is the client API for SyncUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncUserServiceClient interface {
	SyncUserWithAuth(ctx context.Context, in *SyncUserWithAuthRequest, opts ...grpc.CallOption) (*SyncUserWithAuthResponse, error)
}

type syncUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncUserServiceClient(cc grpc.ClientConnInterface) SyncUserServiceClient {
	return &syncUserServiceClient{cc}
}

func (c *syncUserServiceClient) SyncUserWithAuth(ctx context.Context, in *SyncUserWithAuthRequest, opts ...grpc.CallOption) (*SyncUserWithAuthResponse, error) {
	out := new(SyncUserWithAuthResponse)
	err := c.cc.Invoke(ctx, "/auth_service.SyncUserService/SyncUserWithAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncUserServiceServer is the server API for SyncUserService service.
// All implementations must embed UnimplementedSyncUserServiceServer
// for forward compatibility
type SyncUserServiceServer interface {
	SyncUserWithAuth(context.Context, *SyncUserWithAuthRequest) (*SyncUserWithAuthResponse, error)
	mustEmbedUnimplementedSyncUserServiceServer()
}

// UnimplementedSyncUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSyncUserServiceServer struct {
}

func (UnimplementedSyncUserServiceServer) SyncUserWithAuth(context.Context, *SyncUserWithAuthRequest) (*SyncUserWithAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncUserWithAuth not implemented")
}
func (UnimplementedSyncUserServiceServer) mustEmbedUnimplementedSyncUserServiceServer() {}

// UnsafeSyncUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncUserServiceServer will
// result in compilation errors.
type UnsafeSyncUserServiceServer interface {
	mustEmbedUnimplementedSyncUserServiceServer()
}

func RegisterSyncUserServiceServer(s grpc.ServiceRegistrar, srv SyncUserServiceServer) {
	s.RegisterService(&SyncUserService_ServiceDesc, srv)
}

func _SyncUserService_SyncUserWithAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUserWithAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncUserServiceServer).SyncUserWithAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.SyncUserService/SyncUserWithAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncUserServiceServer).SyncUserWithAuth(ctx, req.(*SyncUserWithAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncUserService_ServiceDesc is the grpc.ServiceDesc for SyncUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.SyncUserService",
	HandlerType: (*SyncUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncUserWithAuth",
			Handler:    _SyncUserService_SyncUserWithAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync_user.proto",
}
